language: python
python:
    - 2.7
    - 3.3
before_install:
    - sudo apt-get update
    - sudo apt-get install libopenmpi-dev
    - sudo apt-get install openmpi-bin
      #- pip install numpy
    - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then sudo apt-get install python3-numpy python3-numpy-dev; fi"
    - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then ln -s /usr/lib/python3/dist-packages/numpy ~/virtualenv/python3.3/lib/python3.3/site-packages/; fi"
    - pip install pyzmq --install-option="--zmq=bundled"
    - pip install ipython
    - pip install mpi4py --allow-all-external --allow-unverified mpi4py
    - pip install six
    - pip install sphinx
    - pip install sphinxcontrib-napoleon
    - pip install coverage
    - pip install coveralls
    - pip freeze
install:
    - python setup.py install
    - (cd $TRAVIS_BUILD_DIR && cd docs && make html)
before_script:
    - (cd $TRAVIS_BUILD_DIR && make setup_cluster)
script:
    - (cd $TRAVIS_BUILD_DIR && make test_with_coverage)
after_script:
    - (cd $TRAVIS_BUILD_DIR && make teardown_cluster)
after_success:
    - coverage combine
    - coveralls
