language: python
python:
    - "2.7"
    - "3.3"
before_install:
    - "sudo apt-get install libopenmpi-dev"
    - "sudo apt-get install openmpi-bin"
install:
    - "pip install numpy pyzmq ipython mpi4py six"
before_script: "python distarray/tests/run_ipcluster.py"
script: nosetests
