language: python
python:
    - 2.7
    - 3.3
before_install:
    - sudo apt-get install libopenmpi-dev
    - sudo apt-get install openmpi-bin
    - pip install numpy --use-mirrors
    - pip install pyzmq --install-option="--zmq=bundled" --use-mirrors
    - pip install ipython --use-mirrors
    - pip install mpi4py --use-mirrors
    - pip install six --use-mirrors
install:
    - python setup.py install
before_script:
    - python distarray/tests/run_ipcluster.py
    - sleep 30
script:
    - nosetests -v
