language: python
python:
    - 2.7
    - 3.3
before_install:
    - sudo apt-get install libopenmpi-dev
    - sudo apt-get install openmpi-bin
    - pip install 'numpy==1.7.1' --use-mirrors
    - pip install 'pyzmq==2.2.0.1' --install-option="--zmq=bundled" --use-mirrors
    - pip install 'ipython==1.1.0' --use-mirrors
    - pip install 'mpi4py==1.3' --use-mirrors
    - pip install 'six==1.4.1' --use-mirrors
install:
    - python setup.py install
before_script:
    - (cd $TRAVIS_BUILD_DIR && make setup_cluster)
script:
    - (cd $TRAVIS_BUILD_DIR && make test)
after_script:
    - (cd $TRAVIS_BUILD_DIR && make teardown_cluster)
